services:
  acd-plk-sync:
    container_name: acd-plk-sync
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Asia/Bangkok
      SYNC_LOG_FILE: /logs/sync.log
    volumes:
      - ./logs:/logs
